#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 63
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 2

enum {
  anon_sym_POUND = 1,
  aux_sym_comment_token1 = 2,
  anon_sym_LBRACE = 3,
  anon_sym_COMMA = 4,
  anon_sym_RBRACE = 5,
  anon_sym_EQ = 6,
  anon_sym_pattern = 7,
  anon_sym_file = 8,
  aux_sym_string_token1 = 9,
  anon_sym_DQUOTE = 10,
  aux_sym_quoted_string_text_fragment_token1 = 11,
  anon_sym_BSLASH = 12,
  anon_sym_BSLASH_DQUOTE = 13,
  anon_sym_BSLASH_BSLASH = 14,
  sym_source_file = 15,
  sym_comment = 16,
  sym_regular = 17,
  sym__regular_assignment = 18,
  sym_pattern = 19,
  sym_pattern_variables = 20,
  sym_pattern_values = 21,
  sym_db_template = 22,
  sym_substitutions = 23,
  sym_string = 24,
  sym_quoted_string = 25,
  sym_quoted_string_text_fragment = 26,
  sym_escape_sequence = 27,
  sym_identifier = 28,
  aux_sym_source_file_repeat1 = 29,
  aux_sym_source_file_repeat2 = 30,
  aux_sym_source_file_repeat3 = 31,
  aux_sym_regular_repeat1 = 32,
  aux_sym_pattern_repeat1 = 33,
  aux_sym_pattern_variables_repeat1 = 34,
  aux_sym_pattern_values_repeat1 = 35,
  aux_sym_quoted_string_repeat1 = 36,
  aux_sym_quoted_string_text_fragment_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_pattern] = "pattern",
  [anon_sym_file] = "file",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_string_text_fragment_token1] = "quoted_string_text_fragment_token1",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_BSLASH_DQUOTE] = "\\\"",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym_regular] = "regular",
  [sym__regular_assignment] = "_regular_assignment",
  [sym_pattern] = "pattern",
  [sym_pattern_variables] = "pattern_variables",
  [sym_pattern_values] = "pattern_values",
  [sym_db_template] = "db_template",
  [sym_substitutions] = "substitutions",
  [sym_string] = "string",
  [sym_quoted_string] = "quoted_string",
  [sym_quoted_string_text_fragment] = "quoted_string_text_fragment",
  [sym_escape_sequence] = "escape_sequence",
  [sym_identifier] = "identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_source_file_repeat3] = "source_file_repeat3",
  [aux_sym_regular_repeat1] = "regular_repeat1",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
  [aux_sym_pattern_variables_repeat1] = "pattern_variables_repeat1",
  [aux_sym_pattern_values_repeat1] = "pattern_values_repeat1",
  [aux_sym_quoted_string_repeat1] = "quoted_string_repeat1",
  [aux_sym_quoted_string_text_fragment_repeat1] = "quoted_string_text_fragment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_pattern] = anon_sym_pattern,
  [anon_sym_file] = anon_sym_file,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_string_text_fragment_token1] = aux_sym_quoted_string_text_fragment_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_BSLASH_DQUOTE] = anon_sym_BSLASH_DQUOTE,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym_regular] = sym_regular,
  [sym__regular_assignment] = sym__regular_assignment,
  [sym_pattern] = sym_pattern,
  [sym_pattern_variables] = sym_pattern_variables,
  [sym_pattern_values] = sym_pattern_values,
  [sym_db_template] = sym_db_template,
  [sym_substitutions] = sym_substitutions,
  [sym_string] = sym_string,
  [sym_quoted_string] = sym_quoted_string,
  [sym_quoted_string_text_fragment] = sym_quoted_string_text_fragment,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_identifier] = sym_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_source_file_repeat3] = aux_sym_source_file_repeat3,
  [aux_sym_regular_repeat1] = aux_sym_regular_repeat1,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
  [aux_sym_pattern_variables_repeat1] = aux_sym_pattern_variables_repeat1,
  [aux_sym_pattern_values_repeat1] = aux_sym_pattern_values_repeat1,
  [aux_sym_quoted_string_repeat1] = aux_sym_quoted_string_repeat1,
  [aux_sym_quoted_string_text_fragment_repeat1] = aux_sym_quoted_string_text_fragment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pattern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_file] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_string_text_fragment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_regular] = {
    .visible = true,
    .named = true,
  },
  [sym__regular_assignment] = {
    .visible = false,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern_variables] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern_values] = {
    .visible = true,
    .named = true,
  },
  [sym_db_template] = {
    .visible = true,
    .named = true,
  },
  [sym_substitutions] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string_text_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_regular_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_variables_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_values_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_text_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_file = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_file] = "file",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_file, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '#') ADVANCE(14);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '=') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(29);
      if (lookahead == 'f') ADVANCE(6);
      if (lookahead == 'p') ADVANCE(3);
      if (lookahead == '{') ADVANCE(19);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(12)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '#') ADVANCE(14);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '=') ADVANCE(22);
      if (lookahead == '{') ADVANCE(19);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '#') ADVANCE(15);
      if (lookahead == '\\') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 'i') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(4);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(5);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '#') ADVANCE(14);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '=') ADVANCE(22);
      if (lookahead == 'f') ADVANCE(6);
      if (lookahead == 'p') ADVANCE(3);
      if (lookahead == '{') ADVANCE(19);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(12)
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(28);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_pattern);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_file);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_quoted_string_text_fragment_token1);
      if (lookahead == '#') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_quoted_string_text_fragment_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_BSLASH_DQUOTE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 17},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_pattern] = ACTIONS(1),
    [anon_sym_file] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_BSLASH_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(61),
    [sym_comment] = STATE(1),
    [sym_regular] = STATE(49),
    [sym_pattern] = STATE(48),
    [sym_db_template] = STATE(55),
    [aux_sym_source_file_repeat1] = STATE(36),
    [aux_sym_source_file_repeat2] = STATE(39),
    [aux_sym_source_file_repeat3] = STATE(38),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_pattern] = ACTIONS(9),
    [anon_sym_file] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(13), 1,
      anon_sym_POUND,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      sym_comment,
    STATE(3), 1,
      aux_sym_quoted_string_repeat1,
    STATE(7), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(17), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(19), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(16), 2,
      sym_quoted_string_text_fragment,
      sym_escape_sequence,
  [28] = 7,
    ACTIONS(13), 1,
      anon_sym_POUND,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    STATE(7), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(23), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(26), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(3), 2,
      sym_comment,
      aux_sym_quoted_string_repeat1,
    STATE(16), 2,
      sym_quoted_string_text_fragment,
      sym_escape_sequence,
  [54] = 8,
    ACTIONS(13), 1,
      anon_sym_POUND,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_quoted_string_repeat1,
    STATE(4), 1,
      sym_comment,
    STATE(7), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(17), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(19), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(16), 2,
      sym_quoted_string_text_fragment,
      sym_escape_sequence,
  [82] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_pattern,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_comment,
    STATE(35), 1,
      aux_sym_source_file_repeat1,
    STATE(40), 1,
      aux_sym_source_file_repeat2,
    STATE(48), 1,
      sym_pattern,
    STATE(49), 1,
      sym_regular,
  [110] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 1,
      aux_sym_string_token1,
    ACTIONS(38), 1,
      anon_sym_DQUOTE,
    STATE(22), 1,
      sym_quoted_string,
    STATE(25), 1,
      sym_string,
    STATE(6), 2,
      sym_comment,
      aux_sym_pattern_values_repeat1,
  [133] = 6,
    ACTIONS(13), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      anon_sym_DQUOTE,
    STATE(7), 1,
      sym_comment,
    STATE(10), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(17), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(43), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
  [154] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      sym_comment,
    STATE(11), 1,
      aux_sym_pattern_repeat1,
    STATE(34), 1,
      sym_pattern_values,
    ACTIONS(45), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [175] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(51), 1,
      aux_sym_string_token1,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    STATE(9), 1,
      sym_comment,
    STATE(12), 1,
      aux_sym_pattern_values_repeat1,
    STATE(22), 1,
      sym_quoted_string,
    STATE(25), 1,
      sym_string,
  [200] = 5,
    ACTIONS(13), 1,
      anon_sym_POUND,
    ACTIONS(55), 1,
      anon_sym_DQUOTE,
    ACTIONS(57), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(60), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(10), 2,
      sym_comment,
      aux_sym_quoted_string_text_fragment_repeat1,
  [219] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(34), 1,
      sym_pattern_values,
    STATE(11), 2,
      sym_comment,
      aux_sym_pattern_repeat1,
    ACTIONS(62), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [238] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(51), 1,
      aux_sym_string_token1,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      aux_sym_pattern_values_repeat1,
    STATE(12), 1,
      sym_comment,
    STATE(22), 1,
      sym_quoted_string,
    STATE(25), 1,
      sym_string,
  [263] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      aux_sym_pattern_repeat1,
    STATE(13), 1,
      sym_comment,
    STATE(34), 1,
      sym_pattern_values,
    ACTIONS(69), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [284] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    ACTIONS(73), 1,
      aux_sym_string_token1,
    STATE(47), 1,
      sym__regular_assignment,
    STATE(60), 1,
      sym_identifier,
    STATE(14), 2,
      sym_comment,
      aux_sym_regular_repeat1,
  [304] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(15), 1,
      sym_comment,
    ACTIONS(76), 5,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_string_token1,
      anon_sym_DQUOTE,
  [318] = 4,
    ACTIONS(13), 1,
      anon_sym_POUND,
    STATE(16), 1,
      sym_comment,
    ACTIONS(80), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(78), 3,
      anon_sym_DQUOTE,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
  [334] = 4,
    ACTIONS(13), 1,
      anon_sym_POUND,
    STATE(17), 1,
      sym_comment,
    ACTIONS(84), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(82), 3,
      anon_sym_DQUOTE,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
  [350] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(18), 1,
      sym_comment,
    ACTIONS(86), 5,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_string_token1,
      anon_sym_DQUOTE,
  [364] = 4,
    ACTIONS(13), 1,
      anon_sym_POUND,
    STATE(19), 1,
      sym_comment,
    ACTIONS(90), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(88), 3,
      anon_sym_DQUOTE,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
  [380] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
    ACTIONS(94), 1,
      aux_sym_string_token1,
    STATE(14), 1,
      aux_sym_regular_repeat1,
    STATE(20), 1,
      sym_comment,
    STATE(47), 1,
      sym__regular_assignment,
    STATE(60), 1,
      sym_identifier,
  [402] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(94), 1,
      aux_sym_string_token1,
    ACTIONS(96), 1,
      anon_sym_RBRACE,
    STATE(20), 1,
      aux_sym_regular_repeat1,
    STATE(21), 1,
      sym_comment,
    STATE(47), 1,
      sym__regular_assignment,
    STATE(60), 1,
      sym_identifier,
  [424] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(22), 1,
      sym_comment,
    ACTIONS(98), 5,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_string_token1,
      anon_sym_DQUOTE,
  [438] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(102), 1,
      anon_sym_pattern,
    STATE(48), 1,
      sym_pattern,
    ACTIONS(100), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(23), 2,
      sym_comment,
      aux_sym_source_file_repeat2,
  [456] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(107), 1,
      anon_sym_LBRACE,
    STATE(49), 1,
      sym_regular,
    ACTIONS(105), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(24), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
  [474] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    STATE(25), 1,
      sym_comment,
    ACTIONS(112), 3,
      anon_sym_RBRACE,
      aux_sym_string_token1,
      anon_sym_DQUOTE,
  [489] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(114), 1,
      ts_builtin_sym_end,
    ACTIONS(116), 1,
      anon_sym_file,
    STATE(55), 1,
      sym_db_template,
    STATE(26), 2,
      sym_comment,
      aux_sym_source_file_repeat3,
  [506] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(27), 1,
      sym_comment,
    ACTIONS(119), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [519] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(51), 1,
      aux_sym_string_token1,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    STATE(22), 1,
      sym_quoted_string,
    STATE(28), 1,
      sym_comment,
    STATE(44), 1,
      sym_string,
  [538] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    ACTIONS(123), 1,
      aux_sym_string_token1,
    STATE(45), 1,
      sym_identifier,
    STATE(29), 2,
      sym_comment,
      aux_sym_pattern_variables_repeat1,
  [555] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(30), 1,
      sym_comment,
    ACTIONS(126), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [568] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(31), 1,
      sym_comment,
    ACTIONS(128), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [581] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(94), 1,
      aux_sym_string_token1,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
    STATE(29), 1,
      aux_sym_pattern_variables_repeat1,
    STATE(32), 1,
      sym_comment,
    STATE(45), 1,
      sym_identifier,
  [600] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(94), 1,
      aux_sym_string_token1,
    ACTIONS(132), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      aux_sym_pattern_variables_repeat1,
    STATE(33), 1,
      sym_comment,
    STATE(45), 1,
      sym_identifier,
  [619] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(34), 1,
      sym_comment,
    ACTIONS(134), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [632] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      aux_sym_source_file_repeat1,
    STATE(35), 1,
      sym_comment,
    STATE(49), 1,
      sym_regular,
  [651] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(138), 1,
      ts_builtin_sym_end,
    STATE(24), 1,
      aux_sym_source_file_repeat1,
    STATE(36), 1,
      sym_comment,
    STATE(49), 1,
      sym_regular,
  [670] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(37), 1,
      sym_comment,
    ACTIONS(140), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      aux_sym_string_token1,
  [683] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(11), 1,
      anon_sym_file,
    ACTIONS(138), 1,
      ts_builtin_sym_end,
    STATE(26), 1,
      aux_sym_source_file_repeat3,
    STATE(38), 1,
      sym_comment,
    STATE(55), 1,
      sym_db_template,
  [702] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_pattern,
    ACTIONS(138), 1,
      ts_builtin_sym_end,
    STATE(23), 1,
      aux_sym_source_file_repeat2,
    STATE(39), 1,
      sym_comment,
    STATE(48), 1,
      sym_pattern,
  [721] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_pattern,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    STATE(23), 1,
      aux_sym_source_file_repeat2,
    STATE(40), 1,
      sym_comment,
    STATE(48), 1,
      sym_pattern,
  [740] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(51), 1,
      aux_sym_string_token1,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    STATE(22), 1,
      sym_quoted_string,
    STATE(41), 1,
      sym_comment,
    STATE(54), 1,
      sym_string,
  [759] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(42), 1,
      sym_comment,
    ACTIONS(142), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [772] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(43), 1,
      sym_comment,
    ACTIONS(144), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [784] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(44), 1,
      sym_comment,
    ACTIONS(146), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_string_token1,
  [796] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(148), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      sym_comment,
    ACTIONS(150), 2,
      anon_sym_RBRACE,
      aux_sym_string_token1,
  [810] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(46), 1,
      sym_comment,
    ACTIONS(152), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [822] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(154), 1,
      anon_sym_COMMA,
    STATE(47), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_RBRACE,
      aux_sym_string_token1,
  [836] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(48), 1,
      sym_comment,
    ACTIONS(158), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [848] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(49), 1,
      sym_comment,
    ACTIONS(160), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [860] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(50), 1,
      sym_comment,
    ACTIONS(33), 3,
      anon_sym_RBRACE,
      aux_sym_string_token1,
      anon_sym_DQUOTE,
  [872] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(51), 1,
      sym_comment,
    ACTIONS(162), 2,
      ts_builtin_sym_end,
      anon_sym_file,
  [883] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(52), 1,
      sym_comment,
    ACTIONS(121), 2,
      anon_sym_RBRACE,
      aux_sym_string_token1,
  [894] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(53), 1,
      sym_comment,
    ACTIONS(71), 2,
      anon_sym_RBRACE,
      aux_sym_string_token1,
  [905] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(164), 1,
      anon_sym_LBRACE,
    STATE(51), 1,
      sym_substitutions,
    STATE(54), 1,
      sym_comment,
  [918] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(55), 1,
      sym_comment,
    ACTIONS(166), 2,
      ts_builtin_sym_end,
      anon_sym_file,
  [929] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(56), 1,
      sym_comment,
    ACTIONS(168), 2,
      ts_builtin_sym_end,
      anon_sym_file,
  [940] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(170), 1,
      anon_sym_LBRACE,
    STATE(13), 1,
      sym_pattern_variables,
    STATE(57), 1,
      sym_comment,
  [953] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(58), 1,
      sym_comment,
    ACTIONS(172), 2,
      ts_builtin_sym_end,
      anon_sym_file,
  [964] = 3,
    ACTIONS(13), 1,
      anon_sym_POUND,
    ACTIONS(174), 1,
      aux_sym_comment_token1,
    STATE(59), 1,
      sym_comment,
  [974] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(176), 1,
      anon_sym_EQ,
    STATE(60), 1,
      sym_comment,
  [984] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(178), 1,
      ts_builtin_sym_end,
    STATE(61), 1,
      sym_comment,
  [994] = 1,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 28,
  [SMALL_STATE(4)] = 54,
  [SMALL_STATE(5)] = 82,
  [SMALL_STATE(6)] = 110,
  [SMALL_STATE(7)] = 133,
  [SMALL_STATE(8)] = 154,
  [SMALL_STATE(9)] = 175,
  [SMALL_STATE(10)] = 200,
  [SMALL_STATE(11)] = 219,
  [SMALL_STATE(12)] = 238,
  [SMALL_STATE(13)] = 263,
  [SMALL_STATE(14)] = 284,
  [SMALL_STATE(15)] = 304,
  [SMALL_STATE(16)] = 318,
  [SMALL_STATE(17)] = 334,
  [SMALL_STATE(18)] = 350,
  [SMALL_STATE(19)] = 364,
  [SMALL_STATE(20)] = 380,
  [SMALL_STATE(21)] = 402,
  [SMALL_STATE(22)] = 424,
  [SMALL_STATE(23)] = 438,
  [SMALL_STATE(24)] = 456,
  [SMALL_STATE(25)] = 474,
  [SMALL_STATE(26)] = 489,
  [SMALL_STATE(27)] = 506,
  [SMALL_STATE(28)] = 519,
  [SMALL_STATE(29)] = 538,
  [SMALL_STATE(30)] = 555,
  [SMALL_STATE(31)] = 568,
  [SMALL_STATE(32)] = 581,
  [SMALL_STATE(33)] = 600,
  [SMALL_STATE(34)] = 619,
  [SMALL_STATE(35)] = 632,
  [SMALL_STATE(36)] = 651,
  [SMALL_STATE(37)] = 670,
  [SMALL_STATE(38)] = 683,
  [SMALL_STATE(39)] = 702,
  [SMALL_STATE(40)] = 721,
  [SMALL_STATE(41)] = 740,
  [SMALL_STATE(42)] = 759,
  [SMALL_STATE(43)] = 772,
  [SMALL_STATE(44)] = 784,
  [SMALL_STATE(45)] = 796,
  [SMALL_STATE(46)] = 810,
  [SMALL_STATE(47)] = 822,
  [SMALL_STATE(48)] = 836,
  [SMALL_STATE(49)] = 848,
  [SMALL_STATE(50)] = 860,
  [SMALL_STATE(51)] = 872,
  [SMALL_STATE(52)] = 883,
  [SMALL_STATE(53)] = 894,
  [SMALL_STATE(54)] = 905,
  [SMALL_STATE(55)] = 918,
  [SMALL_STATE(56)] = 929,
  [SMALL_STATE(57)] = 940,
  [SMALL_STATE(58)] = 953,
  [SMALL_STATE(59)] = 964,
  [SMALL_STATE(60)] = 974,
  [SMALL_STATE(61)] = 984,
  [SMALL_STATE(62)] = 994,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2), SHIFT_REPEAT(19),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_string_repeat1, 2), SHIFT_REPEAT(17),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_values_repeat1, 2),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_values_repeat1, 2), SHIFT_REPEAT(22),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_values_repeat1, 2), SHIFT_REPEAT(4),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_string_text_fragment, 1),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string_text_fragment, 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 3),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 2),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 2), SHIFT_REPEAT(19),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 2),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(9),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 2),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_regular_repeat1, 2),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_regular_repeat1, 2), SHIFT_REPEAT(37),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 2),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 1),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_string_repeat1, 1),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_sequence, 1),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape_sequence, 1),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 3),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 1),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(57),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(21),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_values_repeat1, 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 2),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 2), SHIFT_REPEAT(41),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_values, 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_variables_repeat1, 2),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_variables_repeat1, 2), SHIFT_REPEAT(37),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_variables, 3),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_variables, 2),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 1),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_values, 3),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular, 2),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__regular_assignment, 3),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_variables_repeat1, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular, 3),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_regular_repeat1, 1),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_db_template, 3, .production_id = 1),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 1),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_substitutions, 2),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_substitutions, 3),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [178] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_epics_msi(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
