#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 68
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 2

enum {
  anon_sym_POUND = 1,
  aux_sym_comment_token1 = 2,
  anon_sym_LBRACE = 3,
  anon_sym_COMMA = 4,
  anon_sym_RBRACE = 5,
  anon_sym_EQ = 6,
  anon_sym_pattern = 7,
  anon_sym_file = 8,
  aux_sym_identifier_token1 = 9,
  anon_sym_DOLLAR_LBRACE = 10,
  anon_sym_DOLLAR_LPAREN = 11,
  anon_sym_RPAREN = 12,
  sym__macro_expansion_inner = 13,
  anon_sym_DQUOTE = 14,
  aux_sym_quoted_string_text_fragment_token1 = 15,
  anon_sym_BSLASH = 16,
  anon_sym_BSLASH_DQUOTE = 17,
  anon_sym_BSLASH_BSLASH = 18,
  sym_source_file = 19,
  sym_comment = 20,
  sym_regular = 21,
  sym__regular_assignment = 22,
  sym_pattern = 23,
  sym_pattern_variables = 24,
  sym_pattern_values = 25,
  sym_db_template = 26,
  sym_substitutions = 27,
  sym_identifier = 28,
  sym_macro_expansion = 29,
  sym_string = 30,
  sym_quoted_string = 31,
  sym_quoted_string_text_fragment = 32,
  sym_escape_sequence = 33,
  aux_sym_source_file_repeat1 = 34,
  aux_sym_source_file_repeat2 = 35,
  aux_sym_source_file_repeat3 = 36,
  aux_sym_regular_repeat1 = 37,
  aux_sym_pattern_repeat1 = 38,
  aux_sym_pattern_variables_repeat1 = 39,
  aux_sym_pattern_values_repeat1 = 40,
  aux_sym_quoted_string_repeat1 = 41,
  aux_sym_quoted_string_text_fragment_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_pattern] = "pattern",
  [anon_sym_file] = "file",
  [aux_sym_identifier_token1] = "identifier_token1",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [anon_sym_DOLLAR_LPAREN] = "$(",
  [anon_sym_RPAREN] = ")",
  [sym__macro_expansion_inner] = "_macro_expansion_inner",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_string_text_fragment_token1] = "quoted_string_text_fragment_token1",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_BSLASH_DQUOTE] = "\\\"",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym_regular] = "regular",
  [sym__regular_assignment] = "_regular_assignment",
  [sym_pattern] = "pattern",
  [sym_pattern_variables] = "pattern_variables",
  [sym_pattern_values] = "pattern_values",
  [sym_db_template] = "db_template",
  [sym_substitutions] = "substitutions",
  [sym_identifier] = "identifier",
  [sym_macro_expansion] = "macro_expansion",
  [sym_string] = "string",
  [sym_quoted_string] = "quoted_string",
  [sym_quoted_string_text_fragment] = "quoted_string_text_fragment",
  [sym_escape_sequence] = "escape_sequence",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_source_file_repeat3] = "source_file_repeat3",
  [aux_sym_regular_repeat1] = "regular_repeat1",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
  [aux_sym_pattern_variables_repeat1] = "pattern_variables_repeat1",
  [aux_sym_pattern_values_repeat1] = "pattern_values_repeat1",
  [aux_sym_quoted_string_repeat1] = "quoted_string_repeat1",
  [aux_sym_quoted_string_text_fragment_repeat1] = "quoted_string_text_fragment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_pattern] = anon_sym_pattern,
  [anon_sym_file] = anon_sym_file,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [anon_sym_DOLLAR_LPAREN] = anon_sym_DOLLAR_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym__macro_expansion_inner] = sym__macro_expansion_inner,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_string_text_fragment_token1] = aux_sym_quoted_string_text_fragment_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_BSLASH_DQUOTE] = anon_sym_BSLASH_DQUOTE,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym_regular] = sym_regular,
  [sym__regular_assignment] = sym__regular_assignment,
  [sym_pattern] = sym_pattern,
  [sym_pattern_variables] = sym_pattern_variables,
  [sym_pattern_values] = sym_pattern_values,
  [sym_db_template] = sym_db_template,
  [sym_substitutions] = sym_substitutions,
  [sym_identifier] = sym_identifier,
  [sym_macro_expansion] = sym_macro_expansion,
  [sym_string] = sym_string,
  [sym_quoted_string] = sym_quoted_string,
  [sym_quoted_string_text_fragment] = sym_quoted_string_text_fragment,
  [sym_escape_sequence] = sym_escape_sequence,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_source_file_repeat3] = aux_sym_source_file_repeat3,
  [aux_sym_regular_repeat1] = aux_sym_regular_repeat1,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
  [aux_sym_pattern_variables_repeat1] = aux_sym_pattern_variables_repeat1,
  [aux_sym_pattern_values_repeat1] = aux_sym_pattern_values_repeat1,
  [aux_sym_quoted_string_repeat1] = aux_sym_quoted_string_repeat1,
  [aux_sym_quoted_string_text_fragment_repeat1] = aux_sym_quoted_string_text_fragment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pattern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_file] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym__macro_expansion_inner] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_string_text_fragment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_regular] = {
    .visible = true,
    .named = true,
  },
  [sym__regular_assignment] = {
    .visible = false,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern_variables] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern_values] = {
    .visible = true,
    .named = true,
  },
  [sym_db_template] = {
    .visible = true,
    .named = true,
  },
  [sym_substitutions] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_expansion] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string_text_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_regular_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_variables_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_values_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_text_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_file = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_file] = "file",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_file, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '$') ADVANCE(4);
      if (lookahead == ')') ADVANCE(36);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead == 'f') ADVANCE(8);
      if (lookahead == 'p') ADVANCE(5);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '}') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(14)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '$') ADVANCE(4);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '}') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '$') ADVANCE(4);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '$') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '}') ADVANCE(39);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(33);
      if (lookahead == '{') ADVANCE(30);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(6);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '$') ADVANCE(4);
      if (lookahead == ')') ADVANCE(36);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == 'f') ADVANCE(8);
      if (lookahead == 'p') ADVANCE(5);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '}') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(14)
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(42);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '}') ADVANCE(39);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '$') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(35);
      if (lookahead == '{') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_pattern);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_file);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '}') ADVANCE(39);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LPAREN);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LPAREN);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '}') ADVANCE(39);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LPAREN);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__macro_expansion_inner);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '$') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '}') ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__macro_expansion_inner);
      if (lookahead == '(') ADVANCE(34);
      if (lookahead == '{') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '}') ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__macro_expansion_inner);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '}') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_quoted_string_text_fragment_token1);
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '"' || '$' < lookahead) &&
          lookahead != '\\') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_quoted_string_text_fragment_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == '"') ADVANCE(44);
      if (lookahead == '\\') ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_BSLASH_DQUOTE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 20},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 3},
  [66] = {(TSStateId)(-1)},
  [67] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [sym_macro_expansion] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_pattern] = ACTIONS(1),
    [anon_sym_file] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(5),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_BSLASH_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(61),
    [sym_comment] = STATE(1),
    [sym_regular] = STATE(44),
    [sym_pattern] = STATE(50),
    [sym_db_template] = STATE(58),
    [sym_macro_expansion] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(39),
    [aux_sym_source_file_repeat2] = STATE(37),
    [aux_sym_source_file_repeat3] = STATE(34),
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_pattern] = ACTIONS(13),
    [anon_sym_file] = ACTIONS(15),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(5),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      aux_sym_quoted_string_repeat1,
    STATE(11), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(25), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(27), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(2), 2,
      sym_comment,
      sym_macro_expansion,
    STATE(20), 2,
      sym_quoted_string_text_fragment,
      sym_escape_sequence,
  [35] = 9,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    STATE(11), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(31), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(34), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(20), 2,
      sym_quoted_string_text_fragment,
      sym_escape_sequence,
    STATE(3), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_quoted_string_repeat1,
  [68] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    STATE(3), 1,
      aux_sym_quoted_string_repeat1,
    STATE(11), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(25), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(27), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(4), 2,
      sym_comment,
      sym_macro_expansion,
    STATE(20), 2,
      sym_quoted_string_text_fragment,
      sym_escape_sequence,
  [103] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_pattern,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      aux_sym_source_file_repeat1,
    STATE(42), 1,
      aux_sym_source_file_repeat2,
    STATE(44), 1,
      sym_regular,
    STATE(50), 1,
      sym_pattern,
    STATE(5), 2,
      sym_comment,
      sym_macro_expansion,
  [138] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    ACTIONS(43), 1,
      aux_sym_identifier_token1,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    STATE(7), 1,
      aux_sym_pattern_values_repeat1,
    STATE(24), 1,
      sym_quoted_string,
    STATE(32), 1,
      sym_string,
    STATE(6), 2,
      sym_comment,
      sym_macro_expansion,
  [170] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    ACTIONS(49), 1,
      aux_sym_identifier_token1,
    ACTIONS(52), 1,
      anon_sym_DQUOTE,
    STATE(24), 1,
      sym_quoted_string,
    STATE(32), 1,
      sym_string,
    STATE(7), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_pattern_values_repeat1,
  [200] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      aux_sym_pattern_repeat1,
    STATE(38), 1,
      sym_pattern_values,
    STATE(8), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(55), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [228] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      aux_sym_pattern_repeat1,
    STATE(38), 1,
      sym_pattern_values,
    STATE(9), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(59), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [256] = 7,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(66), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(10), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_quoted_string_text_fragment_repeat1,
  [282] = 8,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(68), 1,
      anon_sym_DQUOTE,
    STATE(10), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(25), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(70), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(11), 2,
      sym_comment,
      sym_macro_expansion,
  [310] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      sym_pattern_values,
    ACTIONS(72), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_pattern,
    STATE(12), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_pattern_repeat1,
  [336] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(43), 1,
      aux_sym_identifier_token1,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      aux_sym_pattern_values_repeat1,
    STATE(24), 1,
      sym_quoted_string,
    STATE(32), 1,
      sym_string,
    STATE(13), 2,
      sym_comment,
      sym_macro_expansion,
  [368] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(14), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(79), 5,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
      anon_sym_DQUOTE,
  [389] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(81), 1,
      anon_sym_RBRACE,
    ACTIONS(83), 1,
      aux_sym_identifier_token1,
    STATE(47), 1,
      sym__regular_assignment,
    STATE(63), 1,
      sym_identifier,
    STATE(15), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_regular_repeat1,
  [416] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(88), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(16), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(86), 3,
      anon_sym_DQUOTE,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
  [439] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(92), 1,
      anon_sym_pattern,
    STATE(50), 1,
      sym_pattern,
    ACTIONS(90), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(17), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_source_file_repeat2,
  [464] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(97), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_regular,
    ACTIONS(95), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(18), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_source_file_repeat1,
  [489] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(19), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(100), 5,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
      anon_sym_DQUOTE,
  [510] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(104), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(20), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(102), 3,
      anon_sym_DQUOTE,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
  [533] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    ACTIONS(108), 1,
      aux_sym_identifier_token1,
    STATE(22), 1,
      aux_sym_regular_repeat1,
    STATE(47), 1,
      sym__regular_assignment,
    STATE(63), 1,
      sym_identifier,
    STATE(21), 2,
      sym_comment,
      sym_macro_expansion,
  [562] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(108), 1,
      aux_sym_identifier_token1,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym_regular_repeat1,
    STATE(47), 1,
      sym__regular_assignment,
    STATE(63), 1,
      sym_identifier,
    STATE(22), 2,
      sym_comment,
      sym_macro_expansion,
  [591] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(114), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(23), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(112), 3,
      anon_sym_DQUOTE,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
  [614] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(24), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(116), 5,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
      anon_sym_DQUOTE,
  [635] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(25), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(118), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [655] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(108), 1,
      aux_sym_identifier_token1,
    ACTIONS(120), 1,
      anon_sym_RBRACE,
    STATE(36), 1,
      aux_sym_pattern_variables_repeat1,
    STATE(45), 1,
      sym_identifier,
    STATE(26), 2,
      sym_comment,
      sym_macro_expansion,
  [681] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(27), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(122), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [701] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(28), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(124), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      aux_sym_identifier_token1,
  [721] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
    ACTIONS(128), 1,
      aux_sym_identifier_token1,
    STATE(45), 1,
      sym_identifier,
    STATE(29), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_pattern_variables_repeat1,
  [745] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    ACTIONS(133), 1,
      anon_sym_file,
    STATE(58), 1,
      sym_db_template,
    STATE(30), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_source_file_repeat3,
  [769] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(31), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(136), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [789] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(138), 1,
      anon_sym_COMMA,
    STATE(32), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(140), 3,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
      anon_sym_DQUOTE,
  [811] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(43), 1,
      aux_sym_identifier_token1,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    STATE(24), 1,
      sym_quoted_string,
    STATE(43), 1,
      sym_string,
    STATE(33), 2,
      sym_comment,
      sym_macro_expansion,
  [837] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(15), 1,
      anon_sym_file,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
    STATE(30), 1,
      aux_sym_source_file_repeat3,
    STATE(58), 1,
      sym_db_template,
    STATE(34), 2,
      sym_comment,
      sym_macro_expansion,
  [863] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(35), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(144), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [883] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(108), 1,
      aux_sym_identifier_token1,
    ACTIONS(146), 1,
      anon_sym_RBRACE,
    STATE(29), 1,
      aux_sym_pattern_variables_repeat1,
    STATE(45), 1,
      sym_identifier,
    STATE(36), 2,
      sym_comment,
      sym_macro_expansion,
  [909] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(13), 1,
      anon_sym_pattern,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      aux_sym_source_file_repeat2,
    STATE(50), 1,
      sym_pattern,
    STATE(37), 2,
      sym_comment,
      sym_macro_expansion,
  [935] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(38), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(148), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [955] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
    STATE(18), 1,
      aux_sym_source_file_repeat1,
    STATE(44), 1,
      sym_regular,
    STATE(39), 2,
      sym_comment,
      sym_macro_expansion,
  [981] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(43), 1,
      aux_sym_identifier_token1,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    STATE(24), 1,
      sym_quoted_string,
    STATE(54), 1,
      sym_string,
    STATE(40), 2,
      sym_comment,
      sym_macro_expansion,
  [1007] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(150), 1,
      anon_sym_RBRACE,
    STATE(18), 1,
      aux_sym_source_file_repeat1,
    STATE(44), 1,
      sym_regular,
    STATE(41), 2,
      sym_comment,
      sym_macro_expansion,
  [1033] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(13), 1,
      anon_sym_pattern,
    ACTIONS(150), 1,
      anon_sym_RBRACE,
    STATE(17), 1,
      aux_sym_source_file_repeat2,
    STATE(50), 1,
      sym_pattern,
    STATE(42), 2,
      sym_comment,
      sym_macro_expansion,
  [1059] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(43), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(152), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
  [1078] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(44), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(154), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1097] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    ACTIONS(158), 2,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
    STATE(45), 2,
      sym_comment,
      sym_macro_expansion,
  [1118] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(46), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(47), 3,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
      anon_sym_DQUOTE,
  [1137] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    ACTIONS(162), 2,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
    STATE(47), 2,
      sym_comment,
      sym_macro_expansion,
  [1158] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(48), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(164), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1177] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(49), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(166), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1196] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(50), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(168), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [1215] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(170), 2,
      ts_builtin_sym_end,
      anon_sym_file,
    STATE(51), 2,
      sym_comment,
      sym_macro_expansion,
  [1233] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(81), 2,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
    STATE(52), 2,
      sym_comment,
      sym_macro_expansion,
  [1251] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(172), 2,
      ts_builtin_sym_end,
      anon_sym_file,
    STATE(53), 2,
      sym_comment,
      sym_macro_expansion,
  [1269] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(174), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      sym_substitutions,
    STATE(54), 2,
      sym_comment,
      sym_macro_expansion,
  [1289] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(126), 2,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
    STATE(55), 2,
      sym_comment,
      sym_macro_expansion,
  [1307] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(176), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      sym_pattern_variables,
    STATE(56), 2,
      sym_comment,
      sym_macro_expansion,
  [1327] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(178), 2,
      ts_builtin_sym_end,
      anon_sym_file,
    STATE(57), 2,
      sym_comment,
      sym_macro_expansion,
  [1345] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(180), 2,
      ts_builtin_sym_end,
      anon_sym_file,
    STATE(58), 2,
      sym_comment,
      sym_macro_expansion,
  [1363] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
    STATE(59), 2,
      sym_comment,
      sym_macro_expansion,
  [1380] = 5,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(184), 1,
      aux_sym_comment_token1,
    STATE(60), 2,
      sym_comment,
      sym_macro_expansion,
  [1397] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
    STATE(61), 2,
      sym_comment,
      sym_macro_expansion,
  [1414] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    STATE(62), 2,
      sym_comment,
      sym_macro_expansion,
  [1431] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(188), 1,
      anon_sym_EQ,
    STATE(63), 2,
      sym_comment,
      sym_macro_expansion,
  [1448] = 5,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(190), 1,
      sym__macro_expansion_inner,
    STATE(64), 2,
      sym_comment,
      sym_macro_expansion,
  [1465] = 5,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(192), 1,
      sym__macro_expansion_inner,
    STATE(65), 2,
      sym_comment,
      sym_macro_expansion,
  [1482] = 1,
    ACTIONS(194), 1,
      ts_builtin_sym_end,
  [1486] = 1,
    ACTIONS(196), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 68,
  [SMALL_STATE(5)] = 103,
  [SMALL_STATE(6)] = 138,
  [SMALL_STATE(7)] = 170,
  [SMALL_STATE(8)] = 200,
  [SMALL_STATE(9)] = 228,
  [SMALL_STATE(10)] = 256,
  [SMALL_STATE(11)] = 282,
  [SMALL_STATE(12)] = 310,
  [SMALL_STATE(13)] = 336,
  [SMALL_STATE(14)] = 368,
  [SMALL_STATE(15)] = 389,
  [SMALL_STATE(16)] = 416,
  [SMALL_STATE(17)] = 439,
  [SMALL_STATE(18)] = 464,
  [SMALL_STATE(19)] = 489,
  [SMALL_STATE(20)] = 510,
  [SMALL_STATE(21)] = 533,
  [SMALL_STATE(22)] = 562,
  [SMALL_STATE(23)] = 591,
  [SMALL_STATE(24)] = 614,
  [SMALL_STATE(25)] = 635,
  [SMALL_STATE(26)] = 655,
  [SMALL_STATE(27)] = 681,
  [SMALL_STATE(28)] = 701,
  [SMALL_STATE(29)] = 721,
  [SMALL_STATE(30)] = 745,
  [SMALL_STATE(31)] = 769,
  [SMALL_STATE(32)] = 789,
  [SMALL_STATE(33)] = 811,
  [SMALL_STATE(34)] = 837,
  [SMALL_STATE(35)] = 863,
  [SMALL_STATE(36)] = 883,
  [SMALL_STATE(37)] = 909,
  [SMALL_STATE(38)] = 935,
  [SMALL_STATE(39)] = 955,
  [SMALL_STATE(40)] = 981,
  [SMALL_STATE(41)] = 1007,
  [SMALL_STATE(42)] = 1033,
  [SMALL_STATE(43)] = 1059,
  [SMALL_STATE(44)] = 1078,
  [SMALL_STATE(45)] = 1097,
  [SMALL_STATE(46)] = 1118,
  [SMALL_STATE(47)] = 1137,
  [SMALL_STATE(48)] = 1158,
  [SMALL_STATE(49)] = 1177,
  [SMALL_STATE(50)] = 1196,
  [SMALL_STATE(51)] = 1215,
  [SMALL_STATE(52)] = 1233,
  [SMALL_STATE(53)] = 1251,
  [SMALL_STATE(54)] = 1269,
  [SMALL_STATE(55)] = 1289,
  [SMALL_STATE(56)] = 1307,
  [SMALL_STATE(57)] = 1327,
  [SMALL_STATE(58)] = 1345,
  [SMALL_STATE(59)] = 1363,
  [SMALL_STATE(60)] = 1380,
  [SMALL_STATE(61)] = 1397,
  [SMALL_STATE(62)] = 1414,
  [SMALL_STATE(63)] = 1431,
  [SMALL_STATE(64)] = 1448,
  [SMALL_STATE(65)] = 1465,
  [SMALL_STATE(66)] = 1482,
  [SMALL_STATE(67)] = 1486,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2), SHIFT_REPEAT(23),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_string_repeat1, 2), SHIFT_REPEAT(16),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_values_repeat1, 2),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_values_repeat1, 2), SHIFT_REPEAT(24),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_values_repeat1, 2), SHIFT_REPEAT(2),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 2),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 3),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 2),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 2), SHIFT_REPEAT(23),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 2),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_string_text_fragment, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string_text_fragment, 1),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(13),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_regular_repeat1, 2),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_regular_repeat1, 2), SHIFT_REPEAT(28),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_sequence, 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape_sequence, 1),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(56),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(21),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 3),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 1),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_string_repeat1, 1),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_variables, 3),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_values, 3),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_variables_repeat1, 2),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_variables_repeat1, 2), SHIFT_REPEAT(28),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 2),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 2), SHIFT_REPEAT(40),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_values, 2),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_values_repeat1, 1),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_variables, 2),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 1),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__regular_assignment, 3),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_variables_repeat1, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_regular_repeat1, 1),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular, 2),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular, 3),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 1),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_substitutions, 3),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_db_template, 3, .production_id = 1),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_substitutions, 2),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 1),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [186] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_expansion, 3),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_epics_msi_substitution(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
