#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 86
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 2

enum {
  anon_sym_POUND = 1,
  aux_sym_comment_token1 = 2,
  anon_sym_LBRACE = 3,
  anon_sym_COMMA = 4,
  anon_sym_RBRACE = 5,
  anon_sym_EQ = 6,
  anon_sym_pattern = 7,
  anon_sym_file = 8,
  sym_identifier = 9,
  sym__bareword = 10,
  anon_sym_DQUOTE = 11,
  aux_sym_quoted_string_text_fragment_token1 = 12,
  anon_sym_BSLASH = 13,
  anon_sym_BSLASH_DQUOTE = 14,
  anon_sym_BSLASH_BSLASH = 15,
  anon_sym_DOLLAR_LBRACE = 16,
  aux_sym_macro_expansion_token1 = 17,
  anon_sym_DOLLAR_LPAREN = 18,
  aux_sym_macro_expansion_token2 = 19,
  anon_sym_RPAREN = 20,
  sym_source_file = 21,
  sym_comment = 22,
  sym_regular = 23,
  sym__regular_assignment = 24,
  sym_pattern = 25,
  sym_pattern_variables = 26,
  sym_pattern_values = 27,
  sym_db_template = 28,
  sym_substitutions = 29,
  sym_string = 30,
  sym_quoted_string = 31,
  sym_quoted_string_text_fragment = 32,
  sym_escape_sequence = 33,
  sym_macro_expansion = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_source_file_repeat2 = 36,
  aux_sym_source_file_repeat3 = 37,
  aux_sym_regular_repeat1 = 38,
  aux_sym_pattern_repeat1 = 39,
  aux_sym_pattern_variables_repeat1 = 40,
  aux_sym_pattern_values_repeat1 = 41,
  aux_sym_quoted_string_repeat1 = 42,
  aux_sym_quoted_string_text_fragment_repeat1 = 43,
  aux_sym_macro_expansion_repeat1 = 44,
  aux_sym_macro_expansion_repeat2 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_pattern] = "pattern",
  [anon_sym_file] = "file",
  [sym_identifier] = "identifier",
  [sym__bareword] = "_bareword",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_string_text_fragment_token1] = "quoted_string_text_fragment_token1",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_BSLASH_DQUOTE] = "\\\"",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [aux_sym_macro_expansion_token1] = "macro_expansion_token1",
  [anon_sym_DOLLAR_LPAREN] = "$(",
  [aux_sym_macro_expansion_token2] = "macro_expansion_token2",
  [anon_sym_RPAREN] = ")",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym_regular] = "regular",
  [sym__regular_assignment] = "_regular_assignment",
  [sym_pattern] = "pattern",
  [sym_pattern_variables] = "pattern_variables",
  [sym_pattern_values] = "pattern_values",
  [sym_db_template] = "db_template",
  [sym_substitutions] = "substitutions",
  [sym_string] = "string",
  [sym_quoted_string] = "quoted_string",
  [sym_quoted_string_text_fragment] = "quoted_string_text_fragment",
  [sym_escape_sequence] = "escape_sequence",
  [sym_macro_expansion] = "macro_expansion",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_source_file_repeat3] = "source_file_repeat3",
  [aux_sym_regular_repeat1] = "regular_repeat1",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
  [aux_sym_pattern_variables_repeat1] = "pattern_variables_repeat1",
  [aux_sym_pattern_values_repeat1] = "pattern_values_repeat1",
  [aux_sym_quoted_string_repeat1] = "quoted_string_repeat1",
  [aux_sym_quoted_string_text_fragment_repeat1] = "quoted_string_text_fragment_repeat1",
  [aux_sym_macro_expansion_repeat1] = "macro_expansion_repeat1",
  [aux_sym_macro_expansion_repeat2] = "macro_expansion_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_pattern] = anon_sym_pattern,
  [anon_sym_file] = anon_sym_file,
  [sym_identifier] = sym_identifier,
  [sym__bareword] = sym__bareword,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_string_text_fragment_token1] = aux_sym_quoted_string_text_fragment_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_BSLASH_DQUOTE] = anon_sym_BSLASH_DQUOTE,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [aux_sym_macro_expansion_token1] = aux_sym_macro_expansion_token1,
  [anon_sym_DOLLAR_LPAREN] = anon_sym_DOLLAR_LPAREN,
  [aux_sym_macro_expansion_token2] = aux_sym_macro_expansion_token2,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym_regular] = sym_regular,
  [sym__regular_assignment] = sym__regular_assignment,
  [sym_pattern] = sym_pattern,
  [sym_pattern_variables] = sym_pattern_variables,
  [sym_pattern_values] = sym_pattern_values,
  [sym_db_template] = sym_db_template,
  [sym_substitutions] = sym_substitutions,
  [sym_string] = sym_string,
  [sym_quoted_string] = sym_quoted_string,
  [sym_quoted_string_text_fragment] = sym_quoted_string_text_fragment,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_macro_expansion] = sym_macro_expansion,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_source_file_repeat3] = aux_sym_source_file_repeat3,
  [aux_sym_regular_repeat1] = aux_sym_regular_repeat1,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
  [aux_sym_pattern_variables_repeat1] = aux_sym_pattern_variables_repeat1,
  [aux_sym_pattern_values_repeat1] = aux_sym_pattern_values_repeat1,
  [aux_sym_quoted_string_repeat1] = aux_sym_quoted_string_repeat1,
  [aux_sym_quoted_string_text_fragment_repeat1] = aux_sym_quoted_string_text_fragment_repeat1,
  [aux_sym_macro_expansion_repeat1] = aux_sym_macro_expansion_repeat1,
  [aux_sym_macro_expansion_repeat2] = aux_sym_macro_expansion_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pattern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_file] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__bareword] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_string_text_fragment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_macro_expansion_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOLLAR_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_macro_expansion_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_regular] = {
    .visible = true,
    .named = true,
  },
  [sym__regular_assignment] = {
    .visible = false,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern_variables] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern_values] = {
    .visible = true,
    .named = true,
  },
  [sym_db_template] = {
    .visible = true,
    .named = true,
  },
  [sym_substitutions] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string_text_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_expansion] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_regular_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_variables_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_values_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_text_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_expansion_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_expansion_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_file = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_file] = "file",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_file, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '$') ADVANCE(6);
      if (lookahead == ')') ADVANCE(54);
      if (lookahead == ',') ADVANCE(27);
      if (lookahead == '=') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(37);
      if (lookahead == 'f') ADVANCE(10);
      if (lookahead == 'p') ADVANCE(7);
      if (lookahead == '{') ADVANCE(26);
      if (lookahead == '}') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(16)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '$') ADVANCE(6);
      if (lookahead == ',') ADVANCE(27);
      if (lookahead == '}') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('+' <= lookahead && lookahead <= '<') ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '$') ADVANCE(6);
      if (lookahead == '\\') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '$') ADVANCE(6);
      if (lookahead == ',') ADVANCE(27);
      if (lookahead == '{') ADVANCE(26);
      if (lookahead == '}') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '$') ADVANCE(45);
      if (lookahead == '}') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '$') ADVANCE(52);
      if (lookahead == ')') ADVANCE(54);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 6:
      if (lookahead == '(') ADVANCE(47);
      if (lookahead == '{') ADVANCE(40);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '$') ADVANCE(6);
      if (lookahead == ')') ADVANCE(54);
      if (lookahead == ',') ADVANCE(27);
      if (lookahead == '=') ADVANCE(29);
      if (lookahead == 'f') ADVANCE(10);
      if (lookahead == 'p') ADVANCE(7);
      if (lookahead == '{') ADVANCE(26);
      if (lookahead == '}') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(16)
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(36);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(53);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(46);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '$') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(48);
      if (lookahead == '{') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_pattern);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_file);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__bareword);
      if (lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '<') ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_quoted_string_text_fragment_token1);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '"' || '$' < lookahead) &&
          lookahead != '\\') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_quoted_string_text_fragment_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_BSLASH_DQUOTE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(53);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(46);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_macro_expansion_token1);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '$') ADVANCE(45);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(46);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_macro_expansion_token1);
      if (lookahead == '(') ADVANCE(50);
      if (lookahead == '{') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_macro_expansion_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LPAREN);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LPAREN);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LPAREN);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(53);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LPAREN);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(46);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_macro_expansion_token2);
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '$') ADVANCE(52);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(53);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_macro_expansion_token2);
      if (lookahead == '(') ADVANCE(49);
      if (lookahead == '{') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_macro_expansion_token2);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 5},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 5},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 5},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 4},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 5},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 5},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 5},
  [72] = {.lex_state = 4},
  [73] = {.lex_state = 4},
  [74] = {.lex_state = 3},
  [75] = {.lex_state = 5},
  [76] = {.lex_state = 4},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 5},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 23},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {(TSStateId)(-1)},
  [85] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [sym_macro_expansion] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_pattern] = ACTIONS(1),
    [anon_sym_file] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_BSLASH_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(5),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(82),
    [sym_comment] = STATE(1),
    [sym_regular] = STATE(59),
    [sym_pattern] = STATE(51),
    [sym_db_template] = STATE(80),
    [sym_macro_expansion] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(40),
    [aux_sym_source_file_repeat2] = STATE(41),
    [aux_sym_source_file_repeat3] = STATE(42),
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_pattern] = ACTIONS(13),
    [anon_sym_file] = ACTIONS(15),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(5),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(6), 1,
      aux_sym_quoted_string_repeat1,
    STATE(8), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(21), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(23), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(2), 2,
      sym_comment,
      sym_macro_expansion,
    STATE(16), 2,
      sym_quoted_string_text_fragment,
      sym_escape_sequence,
  [35] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      aux_sym_quoted_string_repeat1,
    STATE(8), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(21), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(23), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(3), 2,
      sym_comment,
      sym_macro_expansion,
    STATE(16), 2,
      sym_quoted_string_text_fragment,
      sym_escape_sequence,
  [70] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    STATE(3), 1,
      aux_sym_quoted_string_repeat1,
    STATE(8), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(21), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(23), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(4), 2,
      sym_comment,
      sym_macro_expansion,
    STATE(16), 2,
      sym_quoted_string_text_fragment,
      sym_escape_sequence,
  [105] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(33), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      aux_sym_quoted_string_repeat1,
    STATE(8), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(21), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(23), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(5), 2,
      sym_comment,
      sym_macro_expansion,
    STATE(16), 2,
      sym_quoted_string_text_fragment,
      sym_escape_sequence,
  [140] = 9,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    STATE(8), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(37), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(40), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(16), 2,
      sym_quoted_string_text_fragment,
      sym_escape_sequence,
    STATE(6), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_quoted_string_repeat1,
  [173] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_pattern,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    STATE(28), 1,
      aux_sym_source_file_repeat2,
    STATE(30), 1,
      aux_sym_source_file_repeat1,
    STATE(51), 1,
      sym_pattern,
    STATE(59), 1,
      sym_regular,
    STATE(7), 2,
      sym_comment,
      sym_macro_expansion,
  [208] = 8,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    STATE(15), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(21), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(47), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(8), 2,
      sym_comment,
      sym_macro_expansion,
  [236] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(51), 1,
      anon_sym_LBRACE,
    STATE(21), 1,
      sym_pattern_values,
    ACTIONS(49), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_pattern,
    STATE(9), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_pattern_repeat1,
  [262] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(54), 1,
      anon_sym_RBRACE,
    ACTIONS(56), 1,
      sym__bareword,
    ACTIONS(58), 1,
      anon_sym_DQUOTE,
    STATE(13), 1,
      aux_sym_pattern_values_repeat1,
    STATE(22), 1,
      sym_quoted_string,
    STATE(34), 1,
      sym_string,
    STATE(10), 2,
      sym_comment,
      sym_macro_expansion,
  [294] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      aux_sym_pattern_repeat1,
    STATE(21), 1,
      sym_pattern_values,
    STATE(11), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(60), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [322] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      aux_sym_pattern_repeat1,
    STATE(21), 1,
      sym_pattern_values,
    STATE(12), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(64), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [350] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    ACTIONS(68), 1,
      sym__bareword,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    STATE(22), 1,
      sym_quoted_string,
    STATE(34), 1,
      sym_string,
    STATE(13), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_pattern_values_repeat1,
  [380] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(56), 1,
      sym__bareword,
    ACTIONS(58), 1,
      anon_sym_DQUOTE,
    ACTIONS(74), 1,
      anon_sym_RBRACE,
    STATE(10), 1,
      aux_sym_pattern_values_repeat1,
    STATE(22), 1,
      sym_quoted_string,
    STATE(34), 1,
      sym_string,
    STATE(14), 2,
      sym_comment,
      sym_macro_expansion,
  [412] = 7,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    ACTIONS(78), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(81), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(15), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_quoted_string_text_fragment_repeat1,
  [438] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(85), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(16), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(83), 3,
      anon_sym_DQUOTE,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
  [461] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(89), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(17), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(87), 3,
      anon_sym_DQUOTE,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
  [484] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(93), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(18), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(91), 3,
      anon_sym_DQUOTE,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
  [507] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(97), 1,
      anon_sym_LBRACE,
    STATE(59), 1,
      sym_regular,
    ACTIONS(95), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(19), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_source_file_repeat1,
  [532] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(102), 1,
      anon_sym_pattern,
    STATE(51), 1,
      sym_pattern,
    ACTIONS(100), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(20), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_source_file_repeat2,
  [557] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(21), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(105), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [577] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(22), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(107), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym__bareword,
      anon_sym_DQUOTE,
  [597] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(23), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(109), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym__bareword,
      anon_sym_DQUOTE,
  [617] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(24), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(111), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym__bareword,
      anon_sym_DQUOTE,
  [637] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    ACTIONS(115), 1,
      sym_identifier,
    STATE(27), 1,
      aux_sym_regular_repeat1,
    STATE(60), 1,
      sym__regular_assignment,
    STATE(25), 2,
      sym_comment,
      sym_macro_expansion,
  [663] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(26), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(117), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [683] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(115), 1,
      sym_identifier,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
    STATE(38), 1,
      aux_sym_regular_repeat1,
    STATE(60), 1,
      sym__regular_assignment,
    STATE(27), 2,
      sym_comment,
      sym_macro_expansion,
  [709] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(13), 1,
      anon_sym_pattern,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    STATE(20), 1,
      aux_sym_source_file_repeat2,
    STATE(51), 1,
      sym_pattern,
    STATE(28), 2,
      sym_comment,
      sym_macro_expansion,
  [735] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(29), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(107), 4,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_identifier,
  [755] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    STATE(19), 1,
      aux_sym_source_file_repeat1,
    STATE(59), 1,
      sym_regular,
    STATE(30), 2,
      sym_comment,
      sym_macro_expansion,
  [781] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
    ACTIONS(125), 1,
      anon_sym_file,
    STATE(80), 1,
      sym_db_template,
    STATE(31), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_source_file_repeat3,
  [805] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(128), 1,
      sym__bareword,
    ACTIONS(130), 1,
      anon_sym_DQUOTE,
    STATE(29), 1,
      sym_quoted_string,
    STATE(65), 1,
      sym_string,
    STATE(32), 2,
      sym_comment,
      sym_macro_expansion,
  [831] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(33), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(109), 4,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_identifier,
  [851] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(132), 1,
      anon_sym_COMMA,
    STATE(34), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(134), 3,
      anon_sym_RBRACE,
      sym__bareword,
      anon_sym_DQUOTE,
  [873] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(128), 1,
      sym__bareword,
    ACTIONS(130), 1,
      anon_sym_DQUOTE,
    STATE(29), 1,
      sym_quoted_string,
    STATE(53), 1,
      sym_string,
    STATE(35), 2,
      sym_comment,
      sym_macro_expansion,
  [899] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(36), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(136), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [919] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(37), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(138), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [939] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
    ACTIONS(142), 1,
      sym_identifier,
    STATE(60), 1,
      sym__regular_assignment,
    STATE(38), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_regular_repeat1,
  [963] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(39), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(145), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [983] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      aux_sym_source_file_repeat1,
    STATE(59), 1,
      sym_regular,
    STATE(40), 2,
      sym_comment,
      sym_macro_expansion,
  [1009] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(13), 1,
      anon_sym_pattern,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      aux_sym_source_file_repeat2,
    STATE(51), 1,
      sym_pattern,
    STATE(41), 2,
      sym_comment,
      sym_macro_expansion,
  [1035] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(15), 1,
      anon_sym_file,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
    STATE(31), 1,
      aux_sym_source_file_repeat3,
    STATE(80), 1,
      sym_db_template,
    STATE(42), 2,
      sym_comment,
      sym_macro_expansion,
  [1061] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(43), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(111), 4,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_identifier,
  [1081] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(149), 1,
      anon_sym_RBRACE,
    ACTIONS(151), 1,
      sym_identifier,
    STATE(48), 1,
      aux_sym_pattern_variables_repeat1,
    STATE(44), 2,
      sym_comment,
      sym_macro_expansion,
  [1104] = 7,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
    ACTIONS(155), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(157), 1,
      aux_sym_macro_expansion_token1,
    ACTIONS(159), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(61), 1,
      aux_sym_macro_expansion_repeat1,
    STATE(45), 2,
      sym_comment,
      sym_macro_expansion,
  [1127] = 7,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(161), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(163), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(165), 1,
      aux_sym_macro_expansion_token2,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_macro_expansion_repeat2,
    STATE(46), 2,
      sym_comment,
      sym_macro_expansion,
  [1150] = 7,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(155), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(157), 1,
      aux_sym_macro_expansion_token1,
    ACTIONS(159), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(167), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      aux_sym_macro_expansion_repeat1,
    STATE(47), 2,
      sym_comment,
      sym_macro_expansion,
  [1173] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(151), 1,
      sym_identifier,
    ACTIONS(169), 1,
      anon_sym_RBRACE,
    STATE(56), 1,
      aux_sym_pattern_variables_repeat1,
    STATE(48), 2,
      sym_comment,
      sym_macro_expansion,
  [1196] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(171), 1,
      anon_sym_COMMA,
    ACTIONS(173), 2,
      anon_sym_RBRACE,
      sym_identifier,
    STATE(49), 2,
      sym_comment,
      sym_macro_expansion,
  [1217] = 7,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(161), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(163), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(165), 1,
      aux_sym_macro_expansion_token2,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_macro_expansion_repeat2,
    STATE(50), 2,
      sym_comment,
      sym_macro_expansion,
  [1240] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(51), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(177), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [1259] = 7,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(155), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(157), 1,
      aux_sym_macro_expansion_token1,
    ACTIONS(159), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(175), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      aux_sym_macro_expansion_repeat1,
    STATE(52), 2,
      sym_comment,
      sym_macro_expansion,
  [1282] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(53), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(179), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_identifier,
  [1301] = 7,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(153), 1,
      anon_sym_RPAREN,
    ACTIONS(161), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(163), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(165), 1,
      aux_sym_macro_expansion_token2,
    STATE(58), 1,
      aux_sym_macro_expansion_repeat2,
    STATE(54), 2,
      sym_comment,
      sym_macro_expansion,
  [1324] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(55), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(181), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1343] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    ACTIONS(185), 1,
      sym_identifier,
    STATE(56), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_pattern_variables_repeat1,
  [1364] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(57), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(188), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1383] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(190), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(193), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(196), 1,
      aux_sym_macro_expansion_token2,
    ACTIONS(199), 1,
      anon_sym_RPAREN,
    STATE(58), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_macro_expansion_repeat2,
  [1404] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(59), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(201), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1423] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(203), 1,
      anon_sym_COMMA,
    ACTIONS(205), 2,
      anon_sym_RBRACE,
      sym_identifier,
    STATE(60), 2,
      sym_comment,
      sym_macro_expansion,
  [1444] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(207), 1,
      anon_sym_RBRACE,
    ACTIONS(209), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(212), 1,
      aux_sym_macro_expansion_token1,
    ACTIONS(215), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(61), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_macro_expansion_repeat1,
  [1465] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(62), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(66), 3,
      anon_sym_RBRACE,
      sym__bareword,
      anon_sym_DQUOTE,
  [1484] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(183), 2,
      anon_sym_RBRACE,
      sym_identifier,
    STATE(63), 2,
      sym_comment,
      sym_macro_expansion,
  [1502] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(155), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(157), 1,
      aux_sym_macro_expansion_token1,
    ACTIONS(159), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(45), 1,
      aux_sym_macro_expansion_repeat1,
    STATE(64), 2,
      sym_comment,
      sym_macro_expansion,
  [1522] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(218), 1,
      anon_sym_LBRACE,
    STATE(77), 1,
      sym_substitutions,
    STATE(65), 2,
      sym_comment,
      sym_macro_expansion,
  [1542] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(161), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(163), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(165), 1,
      aux_sym_macro_expansion_token2,
    STATE(46), 1,
      aux_sym_macro_expansion_repeat2,
    STATE(66), 2,
      sym_comment,
      sym_macro_expansion,
  [1562] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(220), 1,
      anon_sym_LBRACE,
    STATE(11), 1,
      sym_pattern_variables,
    STATE(67), 2,
      sym_comment,
      sym_macro_expansion,
  [1582] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(155), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(157), 1,
      aux_sym_macro_expansion_token1,
    ACTIONS(159), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(47), 1,
      aux_sym_macro_expansion_repeat1,
    STATE(68), 2,
      sym_comment,
      sym_macro_expansion,
  [1602] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(161), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(163), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(165), 1,
      aux_sym_macro_expansion_token2,
    STATE(50), 1,
      aux_sym_macro_expansion_repeat2,
    STATE(69), 2,
      sym_comment,
      sym_macro_expansion,
  [1622] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(222), 2,
      ts_builtin_sym_end,
      anon_sym_file,
    STATE(70), 2,
      sym_comment,
      sym_macro_expansion,
  [1640] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(71), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(224), 4,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
      aux_sym_macro_expansion_token2,
      anon_sym_RPAREN,
  [1654] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(72), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(226), 4,
      anon_sym_RBRACE,
      anon_sym_DOLLAR_LBRACE,
      aux_sym_macro_expansion_token1,
      anon_sym_DOLLAR_LPAREN,
  [1668] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(155), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(157), 1,
      aux_sym_macro_expansion_token1,
    ACTIONS(159), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(52), 1,
      aux_sym_macro_expansion_repeat1,
    STATE(73), 2,
      sym_comment,
      sym_macro_expansion,
  [1688] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(140), 2,
      anon_sym_RBRACE,
      sym_identifier,
    STATE(74), 2,
      sym_comment,
      sym_macro_expansion,
  [1706] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(75), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(226), 4,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
      aux_sym_macro_expansion_token2,
      anon_sym_RPAREN,
  [1720] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(76), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(228), 4,
      anon_sym_RBRACE,
      anon_sym_DOLLAR_LBRACE,
      aux_sym_macro_expansion_token1,
      anon_sym_DOLLAR_LPAREN,
  [1734] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(230), 2,
      ts_builtin_sym_end,
      anon_sym_file,
    STATE(77), 2,
      sym_comment,
      sym_macro_expansion,
  [1752] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(161), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(163), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(165), 1,
      aux_sym_macro_expansion_token2,
    STATE(54), 1,
      aux_sym_macro_expansion_repeat2,
    STATE(78), 2,
      sym_comment,
      sym_macro_expansion,
  [1772] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(232), 2,
      ts_builtin_sym_end,
      anon_sym_file,
    STATE(79), 2,
      sym_comment,
      sym_macro_expansion,
  [1790] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(234), 2,
      ts_builtin_sym_end,
      anon_sym_file,
    STATE(80), 2,
      sym_comment,
      sym_macro_expansion,
  [1808] = 5,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(236), 1,
      aux_sym_comment_token1,
    STATE(81), 2,
      sym_comment,
      sym_macro_expansion,
  [1825] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(238), 1,
      ts_builtin_sym_end,
    STATE(82), 2,
      sym_comment,
      sym_macro_expansion,
  [1842] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(240), 1,
      anon_sym_EQ,
    STATE(83), 2,
      sym_comment,
      sym_macro_expansion,
  [1859] = 1,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
  [1863] = 1,
    ACTIONS(244), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 105,
  [SMALL_STATE(6)] = 140,
  [SMALL_STATE(7)] = 173,
  [SMALL_STATE(8)] = 208,
  [SMALL_STATE(9)] = 236,
  [SMALL_STATE(10)] = 262,
  [SMALL_STATE(11)] = 294,
  [SMALL_STATE(12)] = 322,
  [SMALL_STATE(13)] = 350,
  [SMALL_STATE(14)] = 380,
  [SMALL_STATE(15)] = 412,
  [SMALL_STATE(16)] = 438,
  [SMALL_STATE(17)] = 461,
  [SMALL_STATE(18)] = 484,
  [SMALL_STATE(19)] = 507,
  [SMALL_STATE(20)] = 532,
  [SMALL_STATE(21)] = 557,
  [SMALL_STATE(22)] = 577,
  [SMALL_STATE(23)] = 597,
  [SMALL_STATE(24)] = 617,
  [SMALL_STATE(25)] = 637,
  [SMALL_STATE(26)] = 663,
  [SMALL_STATE(27)] = 683,
  [SMALL_STATE(28)] = 709,
  [SMALL_STATE(29)] = 735,
  [SMALL_STATE(30)] = 755,
  [SMALL_STATE(31)] = 781,
  [SMALL_STATE(32)] = 805,
  [SMALL_STATE(33)] = 831,
  [SMALL_STATE(34)] = 851,
  [SMALL_STATE(35)] = 873,
  [SMALL_STATE(36)] = 899,
  [SMALL_STATE(37)] = 919,
  [SMALL_STATE(38)] = 939,
  [SMALL_STATE(39)] = 963,
  [SMALL_STATE(40)] = 983,
  [SMALL_STATE(41)] = 1009,
  [SMALL_STATE(42)] = 1035,
  [SMALL_STATE(43)] = 1061,
  [SMALL_STATE(44)] = 1081,
  [SMALL_STATE(45)] = 1104,
  [SMALL_STATE(46)] = 1127,
  [SMALL_STATE(47)] = 1150,
  [SMALL_STATE(48)] = 1173,
  [SMALL_STATE(49)] = 1196,
  [SMALL_STATE(50)] = 1217,
  [SMALL_STATE(51)] = 1240,
  [SMALL_STATE(52)] = 1259,
  [SMALL_STATE(53)] = 1282,
  [SMALL_STATE(54)] = 1301,
  [SMALL_STATE(55)] = 1324,
  [SMALL_STATE(56)] = 1343,
  [SMALL_STATE(57)] = 1364,
  [SMALL_STATE(58)] = 1383,
  [SMALL_STATE(59)] = 1404,
  [SMALL_STATE(60)] = 1423,
  [SMALL_STATE(61)] = 1444,
  [SMALL_STATE(62)] = 1465,
  [SMALL_STATE(63)] = 1484,
  [SMALL_STATE(64)] = 1502,
  [SMALL_STATE(65)] = 1522,
  [SMALL_STATE(66)] = 1542,
  [SMALL_STATE(67)] = 1562,
  [SMALL_STATE(68)] = 1582,
  [SMALL_STATE(69)] = 1602,
  [SMALL_STATE(70)] = 1622,
  [SMALL_STATE(71)] = 1640,
  [SMALL_STATE(72)] = 1654,
  [SMALL_STATE(73)] = 1668,
  [SMALL_STATE(74)] = 1688,
  [SMALL_STATE(75)] = 1706,
  [SMALL_STATE(76)] = 1720,
  [SMALL_STATE(77)] = 1734,
  [SMALL_STATE(78)] = 1752,
  [SMALL_STATE(79)] = 1772,
  [SMALL_STATE(80)] = 1790,
  [SMALL_STATE(81)] = 1808,
  [SMALL_STATE(82)] = 1825,
  [SMALL_STATE(83)] = 1842,
  [SMALL_STATE(84)] = 1859,
  [SMALL_STATE(85)] = 1863,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2), SHIFT_REPEAT(18),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_string_repeat1, 2), SHIFT_REPEAT(17),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_string_text_fragment, 1),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string_text_fragment, 1),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(14),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 2),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 3),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_values_repeat1, 2),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_values_repeat1, 2), SHIFT_REPEAT(22),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_values_repeat1, 2), SHIFT_REPEAT(4),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 2),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 2), SHIFT_REPEAT(18),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 2),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_string_repeat1, 1),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_sequence, 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape_sequence, 1),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 1),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 1),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(25),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(67),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 3),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 2),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_values, 3),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 2),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 2), SHIFT_REPEAT(32),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_values_repeat1, 1),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_values, 2),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_variables, 3),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_regular_repeat1, 2),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_regular_repeat1, 2), SHIFT_REPEAT(83),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_variables, 2),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_variables_repeat1, 1),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 1),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__regular_assignment, 3),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular, 3),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_variables_repeat1, 2),
  [185] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_variables_repeat1, 2), SHIFT_REPEAT(49),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular, 2),
  [190] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat2, 2), SHIFT_REPEAT(68),
  [193] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat2, 2), SHIFT_REPEAT(66),
  [196] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat2, 2), SHIFT_REPEAT(71),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat2, 2),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_regular_repeat1, 1),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat1, 2),
  [209] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat1, 2), SHIFT_REPEAT(73),
  [212] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat1, 2), SHIFT_REPEAT(76),
  [215] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat1, 2), SHIFT_REPEAT(69),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_substitutions, 3),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat2, 1),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_expansion, 3),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat1, 1),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_db_template, 3, .production_id = 1),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_substitutions, 2),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 1),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [238] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_expansion, 3),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_epics_msi_substitution(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
